# frozen_string_literal: true

# Generated by generator/generate.rb from Box2D 3.1.0 headers.
# Do not edit this file directly.

require "ffi"
require_relative "native_loader"

module Box2D
  module Native
    extend FFI::Library

    ffi_lib NativeLoader.library_path

      module TOIState
      TOI_STATE_UNKNOWN = 0
      TOI_STATE_FAILED = 1
      TOI_STATE_OVERLAPPED = 2
      TOI_STATE_HIT = 3
      TOI_STATE_SEPARATED = 4
      end

      module BodyType
      STATIC_BODY = 0
      KINEMATIC_BODY = 1
      DYNAMIC_BODY = 2
      BODY_TYPE_COUNT = 3
      end

      module ShapeType
      CIRCLE_SHAPE = 0
      CAPSULE_SHAPE = 1
      SEGMENT_SHAPE = 2
      POLYGON_SHAPE = 3
      CHAIN_SEGMENT_SHAPE = 4
      SHAPE_TYPE_COUNT = 5
      end

      module JointType
      DISTANCE_JOINT = 0
      FILTER_JOINT = 1
      MOTOR_JOINT = 2
      MOUSE_JOINT = 3
      PRISMATIC_JOINT = 4
      REVOLUTE_JOINT = 5
      WELD_JOINT = 6
      WHEEL_JOINT = 7
      end

      module HexColor
      COLOR_ALICE_BLUE = 15792383
      COLOR_ANTIQUE_WHITE = 16444375
      COLOR_AQUA = 65535
      COLOR_AQUAMARINE = 8388564
      COLOR_AZURE = 15794175
      COLOR_BEIGE = 16119260
      COLOR_BISQUE = 16770244
      COLOR_BLACK = 0
      COLOR_BLANCHED_ALMOND = 16772045
      COLOR_BLUE = 255
      COLOR_BLUE_VIOLET = 9055202
      COLOR_BROWN = 10824234
      COLOR_BURLYWOOD = 14596231
      COLOR_CADET_BLUE = 6266528
      COLOR_CHARTREUSE = 8388352
      COLOR_CHOCOLATE = 13789470
      COLOR_CORAL = 16744272
      COLOR_CORNFLOWER_BLUE = 6591981
      COLOR_CORNSILK = 16775388
      COLOR_CRIMSON = 14423100
      COLOR_CYAN = 65535
      COLOR_DARK_BLUE = 139
      COLOR_DARK_CYAN = 35723
      COLOR_DARK_GOLDEN_ROD = 12092939
      COLOR_DARK_GRAY = 11119017
      COLOR_DARK_GREEN = 25600
      COLOR_DARK_KHAKI = 12433259
      COLOR_DARK_MAGENTA = 9109643
      COLOR_DARK_OLIVE_GREEN = 5597999
      COLOR_DARK_ORANGE = 16747520
      COLOR_DARK_ORCHID = 10040012
      COLOR_DARK_RED = 9109504
      COLOR_DARK_SALMON = 15308410
      COLOR_DARK_SEA_GREEN = 9419919
      COLOR_DARK_SLATE_BLUE = 4734347
      COLOR_DARK_SLATE_GRAY = 3100495
      COLOR_DARK_TURQUOISE = 52945
      COLOR_DARK_VIOLET = 9699539
      COLOR_DEEP_PINK = 16716947
      COLOR_DEEP_SKY_BLUE = 49151
      COLOR_DIM_GRAY = 6908265
      COLOR_DODGER_BLUE = 2003199
      COLOR_FIRE_BRICK = 11674146
      COLOR_FLORAL_WHITE = 16775920
      COLOR_FOREST_GREEN = 2263842
      COLOR_FUCHSIA = 16711935
      COLOR_GAINSBORO = 14474460
      COLOR_GHOST_WHITE = 16316671
      COLOR_GOLD = 16766720
      COLOR_GOLDEN_ROD = 14329120
      COLOR_GRAY = 8421504
      COLOR_GREEN = 32768
      COLOR_GREEN_YELLOW = 11403055
      COLOR_HONEY_DEW = 15794160
      COLOR_HOT_PINK = 16738740
      COLOR_INDIAN_RED = 13458524
      COLOR_INDIGO = 4915330
      COLOR_IVORY = 16777200
      COLOR_KHAKI = 15787660
      COLOR_LAVENDER = 15132410
      COLOR_LAVENDER_BLUSH = 16773365
      COLOR_LAWN_GREEN = 8190976
      COLOR_LEMON_CHIFFON = 16775885
      COLOR_LIGHT_BLUE = 11393254
      COLOR_LIGHT_CORAL = 15761536
      COLOR_LIGHT_CYAN = 14745599
      COLOR_LIGHT_GOLDEN_ROD_YELLOW = 16448210
      COLOR_LIGHT_GRAY = 13882323
      COLOR_LIGHT_GREEN = 9498256
      COLOR_LIGHT_PINK = 16758465
      COLOR_LIGHT_SALMON = 16752762
      COLOR_LIGHT_SEA_GREEN = 2142890
      COLOR_LIGHT_SKY_BLUE = 8900346
      COLOR_LIGHT_SLATE_GRAY = 7833753
      COLOR_LIGHT_STEEL_BLUE = 11584734
      COLOR_LIGHT_YELLOW = 16777184
      COLOR_LIME = 65280
      COLOR_LIME_GREEN = 3329330
      COLOR_LINEN = 16445670
      COLOR_MAGENTA = 16711935
      COLOR_MAROON = 8388608
      COLOR_MEDIUM_AQUA_MARINE = 6737322
      COLOR_MEDIUM_BLUE = 205
      COLOR_MEDIUM_ORCHID = 12211667
      COLOR_MEDIUM_PURPLE = 9662683
      COLOR_MEDIUM_SEA_GREEN = 3978097
      COLOR_MEDIUM_SLATE_BLUE = 8087790
      COLOR_MEDIUM_SPRING_GREEN = 64154
      COLOR_MEDIUM_TURQUOISE = 4772300
      COLOR_MEDIUM_VIOLET_RED = 13047173
      COLOR_MIDNIGHT_BLUE = 1644912
      COLOR_MINT_CREAM = 16121850
      COLOR_MISTY_ROSE = 16770273
      COLOR_MOCCASIN = 16770229
      COLOR_NAVAJO_WHITE = 16768685
      COLOR_NAVY = 128
      COLOR_OLD_LACE = 16643558
      COLOR_OLIVE = 8421376
      COLOR_OLIVE_DRAB = 7048739
      COLOR_ORANGE = 16753920
      COLOR_ORANGE_RED = 16729344
      COLOR_ORCHID = 14315734
      COLOR_PALE_GOLDEN_ROD = 15657130
      COLOR_PALE_GREEN = 10025880
      COLOR_PALE_TURQUOISE = 11529966
      COLOR_PALE_VIOLET_RED = 14381203
      COLOR_PAPAYA_WHIP = 16773077
      COLOR_PEACH_PUFF = 16767673
      COLOR_PERU = 13468991
      COLOR_PINK = 16761035
      COLOR_PLUM = 14524637
      COLOR_POWDER_BLUE = 11591910
      COLOR_PURPLE = 8388736
      COLOR_REBECCA_PURPLE = 6697881
      COLOR_RED = 16711680
      COLOR_ROSY_BROWN = 12357519
      COLOR_ROYAL_BLUE = 4286945
      COLOR_SADDLE_BROWN = 9127187
      COLOR_SALMON = 16416882
      COLOR_SANDY_BROWN = 16032864
      COLOR_SEA_GREEN = 3050327
      COLOR_SEA_SHELL = 16774638
      COLOR_SIENNA = 10506797
      COLOR_SILVER = 12632256
      COLOR_SKY_BLUE = 8900331
      COLOR_SLATE_BLUE = 6970061
      COLOR_SLATE_GRAY = 7372944
      COLOR_SNOW = 16775930
      COLOR_SPRING_GREEN = 65407
      COLOR_STEEL_BLUE = 4620980
      COLOR_TAN = 13808780
      COLOR_TEAL = 32896
      COLOR_THISTLE = 14204888
      COLOR_TOMATO = 16737095
      COLOR_TURQUOISE = 4251856
      COLOR_VIOLET = 15631086
      COLOR_WHEAT = 16113331
      COLOR_WHITE = 16777215
      COLOR_WHITE_SMOKE = 16119285
      COLOR_YELLOW = 16776960
      COLOR_YELLOW_GREEN = 10145074
      COLOR_BOX2_DRED = 14430514
      COLOR_BOX2_DBLUE = 3190463
      COLOR_BOX2_DGREEN = 9226532
      COLOR_BOX2_DYELLOW = 16772748
      end
      class Version < FFI::Struct
        layout(
        :major, :int,
        :minor, :int,
        :revision, :int
        )
      end

      class Vec2 < FFI::Struct
        layout(
        :x, :float,
        :y, :float
        )
      end

      class CosSin < FFI::Struct
        layout(
        :cosine, :float,
        :sine, :float
        )
      end

      class Rot < FFI::Struct
        layout(
        :c, :float,
        :s, :float
        )
      end

      class Transform < FFI::Struct
        layout(
        :p, Vec2.by_value,
        :q, Rot.by_value
        )
      end

      class Mat22 < FFI::Struct
        layout(
        :cx, Vec2.by_value,
        :cy, Vec2.by_value
        )
      end

      class AABB < FFI::Struct
        layout(
        :lowerBound, Vec2.by_value,
        :upperBound, Vec2.by_value
        )
      end

      class Plane < FFI::Struct
        layout(
        :normal, Vec2.by_value,
        :offset, :float
        )
      end

      class RayCastInput < FFI::Struct
        layout(
        :origin, Vec2.by_value,
        :translation, Vec2.by_value,
        :maxFraction, :float
        )
      end

      class ShapeProxy < FFI::Struct
        layout(
        :points, [Vec2.by_value, 8],
        :count, :int,
        :radius, :float
        )
      end

      class ShapeCastInput < FFI::Struct
        layout(
        :proxy, ShapeProxy.by_value,
        :translation, Vec2.by_value,
        :maxFraction, :float,
        :canEncroach, :bool
        )
      end

      class CastOutput < FFI::Struct
        layout(
        :normal, Vec2.by_value,
        :point, Vec2.by_value,
        :fraction, :float,
        :iterations, :int,
        :hit, :bool
        )
      end

      class MassData < FFI::Struct
        layout(
        :mass, :float,
        :center, Vec2.by_value,
        :rotationalInertia, :float
        )
      end

      class Circle < FFI::Struct
        layout(
        :center, Vec2.by_value,
        :radius, :float
        )
      end

      class Capsule < FFI::Struct
        layout(
        :center1, Vec2.by_value,
        :center2, Vec2.by_value,
        :radius, :float
        )
      end

      class Polygon < FFI::Struct
        layout(
        :vertices, [Vec2.by_value, 8],
        :normals, [Vec2.by_value, 8],
        :centroid, Vec2.by_value,
        :radius, :float,
        :count, :int
        )
      end

      class Segment < FFI::Struct
        layout(
        :point1, Vec2.by_value,
        :point2, Vec2.by_value
        )
      end

      class ChainSegment < FFI::Struct
        layout(
        :ghost1, Vec2.by_value,
        :segment, Segment.by_value,
        :ghost2, Vec2.by_value,
        :chainId, :int
        )
      end

      class Hull < FFI::Struct
        layout(
        :points, [Vec2.by_value, 8],
        :count, :int
        )
      end

      class SegmentDistanceResult < FFI::Struct
        layout(
        :closest1, Vec2.by_value,
        :closest2, Vec2.by_value,
        :fraction1, :float,
        :fraction2, :float,
        :distanceSquared, :float
        )
      end

      class SimplexCache < FFI::Struct
        layout(
        :count, :uint16,
        :indexA, [:uint8, 3],
        :indexB, [:uint8, 3]
        )
      end

      class DistanceInput < FFI::Struct
        layout(
        :proxyA, ShapeProxy.by_value,
        :proxyB, ShapeProxy.by_value,
        :transformA, Transform.by_value,
        :transformB, Transform.by_value,
        :useRadii, :bool
        )
      end

      class DistanceOutput < FFI::Struct
        layout(
        :pointA, Vec2.by_value,
        :pointB, Vec2.by_value,
        :normal, Vec2.by_value,
        :distance, :float,
        :iterations, :int,
        :simplexCount, :int
        )
      end

      class SimplexVertex < FFI::Struct
        layout(
        :wA, Vec2.by_value,
        :wB, Vec2.by_value,
        :w, Vec2.by_value,
        :a, :float,
        :indexA, :int,
        :indexB, :int
        )
      end

      class Simplex < FFI::Struct
        layout(
        :v1, SimplexVertex.by_value,
        :v2, SimplexVertex.by_value,
        :v3, SimplexVertex.by_value,
        :count, :int
        )
      end

      class ShapeCastPairInput < FFI::Struct
        layout(
        :proxyA, ShapeProxy.by_value,
        :proxyB, ShapeProxy.by_value,
        :transformA, Transform.by_value,
        :transformB, Transform.by_value,
        :translationB, Vec2.by_value,
        :maxFraction, :float,
        :canEncroach, :bool
        )
      end

      class Sweep < FFI::Struct
        layout(
        :localCenter, Vec2.by_value,
        :c1, Vec2.by_value,
        :c2, Vec2.by_value,
        :q1, Rot.by_value,
        :q2, Rot.by_value
        )
      end

      class TOIInput < FFI::Struct
        layout(
        :proxyA, ShapeProxy.by_value,
        :proxyB, ShapeProxy.by_value,
        :sweepA, Sweep.by_value,
        :sweepB, Sweep.by_value,
        :maxFraction, :float
        )
      end

      class TOIOutput < FFI::Struct
        layout(
        :state, :int,
        :fraction, :float
        )
      end

      class ManifoldPoint < FFI::Struct
        layout(
        :point, Vec2.by_value,
        :anchorA, Vec2.by_value,
        :anchorB, Vec2.by_value,
        :separation, :float,
        :normalImpulse, :float,
        :tangentImpulse, :float,
        :totalNormalImpulse, :float,
        :normalVelocity, :float,
        :id, :uint16,
        :persisted, :bool
        )
      end

      class Manifold < FFI::Struct
        layout(
        :normal, Vec2.by_value,
        :rollingImpulse, :float,
        :points, [ManifoldPoint.by_value, 2],
        :pointCount, :int
        )
      end

      class DynamicTree < FFI::Struct
        layout(
        :nodes, :pointer,
        :root, :int,
        :nodeCount, :int,
        :nodeCapacity, :int,
        :freeList, :int,
        :proxyCount, :int,
        :leafIndices, :pointer,
        :leafBoxes, :pointer,
        :leafCenters, :pointer,
        :binIndices, :pointer,
        :rebuildCapacity, :int
        )
      end

      class TreeStats < FFI::Struct
        layout(
        :nodeVisits, :int,
        :leafVisits, :int
        )
      end

      class PlaneResult < FFI::Struct
        layout(
        :plane, Plane.by_value,
        :hit, :bool
        )
      end

      class CollisionPlane < FFI::Struct
        layout(
        :plane, Plane.by_value,
        :pushLimit, :float,
        :push, :float,
        :clipVelocity, :bool
        )
      end

      class PlaneSolverResult < FFI::Struct
        layout(
        :position, Vec2.by_value,
        :iterationCount, :int
        )
      end

      class WorldId < FFI::Struct
        layout(
        :index1, :uint16,
        :generation, :uint16
        )
      end

      class BodyId < FFI::Struct
        layout(
        :index1, :int32,
        :world0, :uint16,
        :generation, :uint16
        )
      end

      class ShapeId < FFI::Struct
        layout(
        :index1, :int32,
        :world0, :uint16,
        :generation, :uint16
        )
      end

      class ChainId < FFI::Struct
        layout(
        :index1, :int32,
        :world0, :uint16,
        :generation, :uint16
        )
      end

      class JointId < FFI::Struct
        layout(
        :index1, :int32,
        :world0, :uint16,
        :generation, :uint16
        )
      end

      class RayResult < FFI::Struct
        layout(
        :shapeId, ShapeId.by_value,
        :point, Vec2.by_value,
        :normal, Vec2.by_value,
        :fraction, :float,
        :nodeVisits, :int,
        :leafVisits, :int,
        :hit, :bool
        )
      end

      class WorldDef < FFI::Struct
        layout(
        :gravity, Vec2.by_value,
        :restitutionThreshold, :float,
        :hitEventThreshold, :float,
        :contactHertz, :float,
        :contactDampingRatio, :float,
        :maxContactPushSpeed, :float,
        :jointHertz, :float,
        :jointDampingRatio, :float,
        :maximumLinearSpeed, :float,
        :frictionCallback, :pointer,
        :restitutionCallback, :pointer,
        :enableSleep, :bool,
        :enableContinuous, :bool,
        :workerCount, :int,
        :enqueueTask, :pointer,
        :finishTask, :pointer,
        :userTaskContext, :pointer,
        :userData, :pointer,
        :internalValue, :int
        )
      end

      class BodyDef < FFI::Struct
        layout(
        :type, :int,
        :position, Vec2.by_value,
        :rotation, Rot.by_value,
        :linearVelocity, Vec2.by_value,
        :angularVelocity, :float,
        :linearDamping, :float,
        :angularDamping, :float,
        :gravityScale, :float,
        :sleepThreshold, :float,
        :name, :pointer,
        :userData, :pointer,
        :enableSleep, :bool,
        :isAwake, :bool,
        :fixedRotation, :bool,
        :isBullet, :bool,
        :isEnabled, :bool,
        :allowFastRotation, :bool,
        :internalValue, :int
        )
      end

      class Filter < FFI::Struct
        layout(
        :categoryBits, :uint64,
        :maskBits, :uint64,
        :groupIndex, :int
        )
      end

      class QueryFilter < FFI::Struct
        layout(
        :categoryBits, :uint64,
        :maskBits, :uint64
        )
      end

      class SurfaceMaterial < FFI::Struct
        layout(
        :friction, :float,
        :restitution, :float,
        :rollingResistance, :float,
        :tangentSpeed, :float,
        :userMaterialId, :int,
        :customColor, :uint32
        )
      end

      class ShapeDef < FFI::Struct
        layout(
        :userData, :pointer,
        :material, SurfaceMaterial.by_value,
        :density, :float,
        :filter, Filter.by_value,
        :isSensor, :bool,
        :enableSensorEvents, :bool,
        :enableContactEvents, :bool,
        :enableHitEvents, :bool,
        :enablePreSolveEvents, :bool,
        :invokeContactCreation, :bool,
        :updateBodyMass, :bool,
        :internalValue, :int
        )
      end

      class ChainDef < FFI::Struct
        layout(
        :userData, :pointer,
        :points, :pointer,
        :count, :int,
        :materials, :pointer,
        :materialCount, :int,
        :filter, Filter.by_value,
        :isLoop, :bool,
        :enableSensorEvents, :bool,
        :internalValue, :int
        )
      end

      class Profile < FFI::Struct
        layout(
        :step, :float,
        :pairs, :float,
        :collide, :float,
        :solve, :float,
        :mergeIslands, :float,
        :prepareStages, :float,
        :solveConstraints, :float,
        :prepareConstraints, :float,
        :integrateVelocities, :float,
        :warmStart, :float,
        :solveImpulses, :float,
        :integratePositions, :float,
        :relaxImpulses, :float,
        :applyRestitution, :float,
        :storeImpulses, :float,
        :splitIslands, :float,
        :transforms, :float,
        :hitEvents, :float,
        :refit, :float,
        :bullets, :float,
        :sleepIslands, :float,
        :sensors, :float
        )
      end

      class Counters < FFI::Struct
        layout(
        :bodyCount, :int,
        :shapeCount, :int,
        :contactCount, :int,
        :jointCount, :int,
        :islandCount, :int,
        :stackUsed, :int,
        :staticTreeHeight, :int,
        :treeHeight, :int,
        :byteCount, :int,
        :taskCount, :int,
        :colorCounts, [:int, 12]
        )
      end

      class DistanceJointDef < FFI::Struct
        layout(
        :bodyIdA, BodyId.by_value,
        :bodyIdB, BodyId.by_value,
        :localAnchorA, Vec2.by_value,
        :localAnchorB, Vec2.by_value,
        :length, :float,
        :enableSpring, :bool,
        :hertz, :float,
        :dampingRatio, :float,
        :enableLimit, :bool,
        :minLength, :float,
        :maxLength, :float,
        :enableMotor, :bool,
        :maxMotorForce, :float,
        :motorSpeed, :float,
        :collideConnected, :bool,
        :userData, :pointer,
        :internalValue, :int
        )
      end

      class MotorJointDef < FFI::Struct
        layout(
        :bodyIdA, BodyId.by_value,
        :bodyIdB, BodyId.by_value,
        :linearOffset, Vec2.by_value,
        :angularOffset, :float,
        :maxForce, :float,
        :maxTorque, :float,
        :correctionFactor, :float,
        :collideConnected, :bool,
        :userData, :pointer,
        :internalValue, :int
        )
      end

      class MouseJointDef < FFI::Struct
        layout(
        :bodyIdA, BodyId.by_value,
        :bodyIdB, BodyId.by_value,
        :target, Vec2.by_value,
        :hertz, :float,
        :dampingRatio, :float,
        :maxForce, :float,
        :collideConnected, :bool,
        :userData, :pointer,
        :internalValue, :int
        )
      end

      class FilterJointDef < FFI::Struct
        layout(
        :bodyIdA, BodyId.by_value,
        :bodyIdB, BodyId.by_value,
        :userData, :pointer,
        :internalValue, :int
        )
      end

      class PrismaticJointDef < FFI::Struct
        layout(
        :bodyIdA, BodyId.by_value,
        :bodyIdB, BodyId.by_value,
        :localAnchorA, Vec2.by_value,
        :localAnchorB, Vec2.by_value,
        :localAxisA, Vec2.by_value,
        :referenceAngle, :float,
        :enableSpring, :bool,
        :hertz, :float,
        :dampingRatio, :float,
        :enableLimit, :bool,
        :lowerTranslation, :float,
        :upperTranslation, :float,
        :enableMotor, :bool,
        :maxMotorForce, :float,
        :motorSpeed, :float,
        :collideConnected, :bool,
        :userData, :pointer,
        :internalValue, :int
        )
      end

      class RevoluteJointDef < FFI::Struct
        layout(
        :bodyIdA, BodyId.by_value,
        :bodyIdB, BodyId.by_value,
        :localAnchorA, Vec2.by_value,
        :localAnchorB, Vec2.by_value,
        :referenceAngle, :float,
        :enableSpring, :bool,
        :hertz, :float,
        :dampingRatio, :float,
        :enableLimit, :bool,
        :lowerAngle, :float,
        :upperAngle, :float,
        :enableMotor, :bool,
        :maxMotorTorque, :float,
        :motorSpeed, :float,
        :drawSize, :float,
        :collideConnected, :bool,
        :userData, :pointer,
        :internalValue, :int
        )
      end

      class WeldJointDef < FFI::Struct
        layout(
        :bodyIdA, BodyId.by_value,
        :bodyIdB, BodyId.by_value,
        :localAnchorA, Vec2.by_value,
        :localAnchorB, Vec2.by_value,
        :referenceAngle, :float,
        :linearHertz, :float,
        :angularHertz, :float,
        :linearDampingRatio, :float,
        :angularDampingRatio, :float,
        :collideConnected, :bool,
        :userData, :pointer,
        :internalValue, :int
        )
      end

      class WheelJointDef < FFI::Struct
        layout(
        :bodyIdA, BodyId.by_value,
        :bodyIdB, BodyId.by_value,
        :localAnchorA, Vec2.by_value,
        :localAnchorB, Vec2.by_value,
        :localAxisA, Vec2.by_value,
        :enableSpring, :bool,
        :hertz, :float,
        :dampingRatio, :float,
        :enableLimit, :bool,
        :lowerTranslation, :float,
        :upperTranslation, :float,
        :enableMotor, :bool,
        :maxMotorTorque, :float,
        :motorSpeed, :float,
        :collideConnected, :bool,
        :userData, :pointer,
        :internalValue, :int
        )
      end

      class ExplosionDef < FFI::Struct
        layout(
        :maskBits, :uint64,
        :position, Vec2.by_value,
        :radius, :float,
        :falloff, :float,
        :impulsePerLength, :float
        )
      end

      class SensorBeginTouchEvent < FFI::Struct
        layout(
        :sensorShapeId, ShapeId.by_value,
        :visitorShapeId, ShapeId.by_value
        )
      end

      class SensorEndTouchEvent < FFI::Struct
        layout(
        :sensorShapeId, ShapeId.by_value,
        :visitorShapeId, ShapeId.by_value
        )
      end

      class SensorEvents < FFI::Struct
        layout(
        :beginEvents, :pointer,
        :endEvents, :pointer,
        :beginCount, :int,
        :endCount, :int
        )
      end

      class ContactBeginTouchEvent < FFI::Struct
        layout(
        :shapeIdA, ShapeId.by_value,
        :shapeIdB, ShapeId.by_value,
        :manifold, Manifold.by_value
        )
      end

      class ContactEndTouchEvent < FFI::Struct
        layout(
        :shapeIdA, ShapeId.by_value,
        :shapeIdB, ShapeId.by_value
        )
      end

      class ContactHitEvent < FFI::Struct
        layout(
        :shapeIdA, ShapeId.by_value,
        :shapeIdB, ShapeId.by_value,
        :point, Vec2.by_value,
        :normal, Vec2.by_value,
        :approachSpeed, :float
        )
      end

      class ContactEvents < FFI::Struct
        layout(
        :beginEvents, :pointer,
        :endEvents, :pointer,
        :hitEvents, :pointer,
        :beginCount, :int,
        :endCount, :int,
        :hitCount, :int
        )
      end

      class BodyMoveEvent < FFI::Struct
        layout(
        :transform, Transform.by_value,
        :bodyId, BodyId.by_value,
        :userData, :pointer,
        :fellAsleep, :bool
        )
      end

      class BodyEvents < FFI::Struct
        layout(
        :moveEvents, :pointer,
        :moveCount, :int
        )
      end

      class ContactData < FFI::Struct
        layout(
        :shapeIdA, ShapeId.by_value,
        :shapeIdB, ShapeId.by_value,
        :manifold, Manifold.by_value
        )
      end

      class DebugDraw < FFI::Struct
        layout(
        :DrawPolygonFcn, :pointer,
        :DrawSolidPolygonFcn, :pointer,
        :DrawCircleFcn, :pointer,
        :DrawSolidCircleFcn, :pointer,
        :DrawSolidCapsuleFcn, :pointer,
        :DrawSegmentFcn, :pointer,
        :DrawTransformFcn, :pointer,
        :DrawPointFcn, :pointer,
        :DrawStringFcn, :pointer,
        :drawingBounds, AABB.by_value,
        :useDrawingBounds, :bool,
        :drawShapes, :bool,
        :drawJoints, :bool,
        :drawJointExtras, :bool,
        :drawBounds, :bool,
        :drawMass, :bool,
        :drawBodyNames, :bool,
        :drawContacts, :bool,
        :drawGraphColors, :bool,
        :drawContactNormals, :bool,
        :drawContactImpulses, :bool,
        :drawContactFeatures, :bool,
        :drawFrictionImpulses, :bool,
        :drawIslands, :bool,
        :context, :pointer
        )
      end
    ABI_LAYOUTS = {
      "Version" => {size: 12, alignment: 4, offsets: {major: 0, minor: 4, revision: 8}},
      "Vec2" => {size: 8, alignment: 4, offsets: {x: 0, y: 4}},
      "CosSin" => {size: 8, alignment: 4, offsets: {cosine: 0, sine: 4}},
      "Rot" => {size: 8, alignment: 4, offsets: {c: 0, s: 4}},
      "Transform" => {size: 16, alignment: 4, offsets: {p: 0, q: 8}},
      "Mat22" => {size: 16, alignment: 4, offsets: {cx: 0, cy: 8}},
      "AABB" => {size: 16, alignment: 4, offsets: {lowerBound: 0, upperBound: 8}},
      "Plane" => {size: 12, alignment: 4, offsets: {normal: 0, offset: 8}},
      "RayCastInput" => {size: 20, alignment: 4, offsets: {origin: 0, translation: 8, maxFraction: 16}},
      "ShapeProxy" => {size: 72, alignment: 4, offsets: {points: 0, count: 64, radius: 68}},
      "ShapeCastInput" => {size: 88, alignment: 4, offsets: {proxy: 0, translation: 72, maxFraction: 80, canEncroach: 84}},
      "CastOutput" => {size: 28, alignment: 4, offsets: {normal: 0, point: 8, fraction: 16, iterations: 20, hit: 24}},
      "MassData" => {size: 16, alignment: 4, offsets: {mass: 0, center: 4, rotationalInertia: 12}},
      "Circle" => {size: 12, alignment: 4, offsets: {center: 0, radius: 8}},
      "Capsule" => {size: 20, alignment: 4, offsets: {center1: 0, center2: 8, radius: 16}},
      "Polygon" => {size: 144, alignment: 4, offsets: {vertices: 0, normals: 64, centroid: 128, radius: 136, count: 140}},
      "Segment" => {size: 16, alignment: 4, offsets: {point1: 0, point2: 8}},
      "ChainSegment" => {size: 36, alignment: 4, offsets: {ghost1: 0, segment: 8, ghost2: 24, chainId: 32}},
      "Hull" => {size: 68, alignment: 4, offsets: {points: 0, count: 64}},
      "SegmentDistanceResult" => {size: 28, alignment: 4, offsets: {closest1: 0, closest2: 8, fraction1: 16, fraction2: 20, distanceSquared: 24}},
      "SimplexCache" => {size: 8, alignment: 2, offsets: {count: 0, indexA: 2, indexB: 5}},
      "DistanceInput" => {size: 180, alignment: 4, offsets: {proxyA: 0, proxyB: 72, transformA: 144, transformB: 160, useRadii: 176}},
      "DistanceOutput" => {size: 36, alignment: 4, offsets: {pointA: 0, pointB: 8, normal: 16, distance: 24, iterations: 28, simplexCount: 32}},
      "SimplexVertex" => {size: 36, alignment: 4, offsets: {wA: 0, wB: 8, w: 16, a: 24, indexA: 28, indexB: 32}},
      "Simplex" => {size: 112, alignment: 4, offsets: {v1: 0, v2: 36, v3: 72, count: 108}},
      "ShapeCastPairInput" => {size: 192, alignment: 4, offsets: {proxyA: 0, proxyB: 72, transformA: 144, transformB: 160, translationB: 176, maxFraction: 184, canEncroach: 188}},
      "Sweep" => {size: 40, alignment: 4, offsets: {localCenter: 0, c1: 8, c2: 16, q1: 24, q2: 32}},
      "TOIInput" => {size: 228, alignment: 4, offsets: {proxyA: 0, proxyB: 72, sweepA: 144, sweepB: 184, maxFraction: 224}},
      "TOIOutput" => {size: 8, alignment: 4, offsets: {state: 0, fraction: 4}},
      "ManifoldPoint" => {size: 48, alignment: 4, offsets: {point: 0, anchorA: 8, anchorB: 16, separation: 24, normalImpulse: 28, tangentImpulse: 32, totalNormalImpulse: 36, normalVelocity: 40, id: 44, persisted: 46}},
      "Manifold" => {size: 112, alignment: 4, offsets: {normal: 0, rollingImpulse: 8, points: 12, pointCount: 108}},
      "DynamicTree" => {size: 72, alignment: 8, offsets: {nodes: 0, root: 8, nodeCount: 12, nodeCapacity: 16, freeList: 20, proxyCount: 24, leafIndices: 32, leafBoxes: 40, leafCenters: 48, binIndices: 56, rebuildCapacity: 64}},
      "TreeStats" => {size: 8, alignment: 4, offsets: {nodeVisits: 0, leafVisits: 4}},
      "PlaneResult" => {size: 16, alignment: 4, offsets: {plane: 0, hit: 12}},
      "CollisionPlane" => {size: 24, alignment: 4, offsets: {plane: 0, pushLimit: 12, push: 16, clipVelocity: 20}},
      "PlaneSolverResult" => {size: 12, alignment: 4, offsets: {position: 0, iterationCount: 8}},
      "WorldId" => {size: 4, alignment: 2, offsets: {index1: 0, generation: 2}},
      "BodyId" => {size: 8, alignment: 4, offsets: {index1: 0, world0: 4, generation: 6}},
      "ShapeId" => {size: 8, alignment: 4, offsets: {index1: 0, world0: 4, generation: 6}},
      "ChainId" => {size: 8, alignment: 4, offsets: {index1: 0, world0: 4, generation: 6}},
      "JointId" => {size: 8, alignment: 4, offsets: {index1: 0, world0: 4, generation: 6}},
      "RayResult" => {size: 40, alignment: 4, offsets: {shapeId: 0, point: 8, normal: 16, fraction: 24, nodeVisits: 28, leafVisits: 32, hit: 36}},
      "WorldDef" => {size: 104, alignment: 8, offsets: {gravity: 0, restitutionThreshold: 8, hitEventThreshold: 12, contactHertz: 16, contactDampingRatio: 20, maxContactPushSpeed: 24, jointHertz: 28, jointDampingRatio: 32, maximumLinearSpeed: 36, frictionCallback: 40, restitutionCallback: 48, enableSleep: 56, enableContinuous: 57, workerCount: 60, enqueueTask: 64, finishTask: 72, userTaskContext: 80, userData: 88, internalValue: 96}},
      "BodyDef" => {size: 80, alignment: 8, offsets: {type: 0, position: 4, rotation: 12, linearVelocity: 20, angularVelocity: 28, linearDamping: 32, angularDamping: 36, gravityScale: 40, sleepThreshold: 44, name: 48, userData: 56, enableSleep: 64, isAwake: 65, fixedRotation: 66, isBullet: 67, isEnabled: 68, allowFastRotation: 69, internalValue: 72}},
      "Filter" => {size: 24, alignment: 8, offsets: {categoryBits: 0, maskBits: 8, groupIndex: 16}},
      "QueryFilter" => {size: 16, alignment: 8, offsets: {categoryBits: 0, maskBits: 8}},
      "SurfaceMaterial" => {size: 24, alignment: 4, offsets: {friction: 0, restitution: 4, rollingResistance: 8, tangentSpeed: 12, userMaterialId: 16, customColor: 20}},
      "ShapeDef" => {size: 80, alignment: 8, offsets: {userData: 0, material: 8, density: 32, filter: 40, isSensor: 64, enableSensorEvents: 65, enableContactEvents: 66, enableHitEvents: 67, enablePreSolveEvents: 68, invokeContactCreation: 69, updateBodyMass: 70, internalValue: 72}},
      "ChainDef" => {size: 72, alignment: 8, offsets: {userData: 0, points: 8, count: 16, materials: 24, materialCount: 32, filter: 40, isLoop: 64, enableSensorEvents: 65, internalValue: 68}},
      "Profile" => {size: 88, alignment: 4, offsets: {step: 0, pairs: 4, collide: 8, solve: 12, mergeIslands: 16, prepareStages: 20, solveConstraints: 24, prepareConstraints: 28, integrateVelocities: 32, warmStart: 36, solveImpulses: 40, integratePositions: 44, relaxImpulses: 48, applyRestitution: 52, storeImpulses: 56, splitIslands: 60, transforms: 64, hitEvents: 68, refit: 72, bullets: 76, sleepIslands: 80, sensors: 84}},
      "Counters" => {size: 88, alignment: 4, offsets: {bodyCount: 0, shapeCount: 4, contactCount: 8, jointCount: 12, islandCount: 16, stackUsed: 20, staticTreeHeight: 24, treeHeight: 28, byteCount: 32, taskCount: 36, colorCounts: 40}},
      "DistanceJointDef" => {size: 96, alignment: 8, offsets: {bodyIdA: 0, bodyIdB: 8, localAnchorA: 16, localAnchorB: 24, length: 32, enableSpring: 36, hertz: 40, dampingRatio: 44, enableLimit: 48, minLength: 52, maxLength: 56, enableMotor: 60, maxMotorForce: 64, motorSpeed: 68, collideConnected: 72, userData: 80, internalValue: 88}},
      "MotorJointDef" => {size: 64, alignment: 8, offsets: {bodyIdA: 0, bodyIdB: 8, linearOffset: 16, angularOffset: 24, maxForce: 28, maxTorque: 32, correctionFactor: 36, collideConnected: 40, userData: 48, internalValue: 56}},
      "MouseJointDef" => {size: 56, alignment: 8, offsets: {bodyIdA: 0, bodyIdB: 8, target: 16, hertz: 24, dampingRatio: 28, maxForce: 32, collideConnected: 36, userData: 40, internalValue: 48}},
      "FilterJointDef" => {size: 32, alignment: 8, offsets: {bodyIdA: 0, bodyIdB: 8, userData: 16, internalValue: 24}},
      "PrismaticJointDef" => {size: 104, alignment: 8, offsets: {bodyIdA: 0, bodyIdB: 8, localAnchorA: 16, localAnchorB: 24, localAxisA: 32, referenceAngle: 40, enableSpring: 44, hertz: 48, dampingRatio: 52, enableLimit: 56, lowerTranslation: 60, upperTranslation: 64, enableMotor: 68, maxMotorForce: 72, motorSpeed: 76, collideConnected: 80, userData: 88, internalValue: 96}},
      "RevoluteJointDef" => {size: 96, alignment: 8, offsets: {bodyIdA: 0, bodyIdB: 8, localAnchorA: 16, localAnchorB: 24, referenceAngle: 32, enableSpring: 36, hertz: 40, dampingRatio: 44, enableLimit: 48, lowerAngle: 52, upperAngle: 56, enableMotor: 60, maxMotorTorque: 64, motorSpeed: 68, drawSize: 72, collideConnected: 76, userData: 80, internalValue: 88}},
      "WeldJointDef" => {size: 72, alignment: 8, offsets: {bodyIdA: 0, bodyIdB: 8, localAnchorA: 16, localAnchorB: 24, referenceAngle: 32, linearHertz: 36, angularHertz: 40, linearDampingRatio: 44, angularDampingRatio: 48, collideConnected: 52, userData: 56, internalValue: 64}},
      "WheelJointDef" => {size: 96, alignment: 8, offsets: {bodyIdA: 0, bodyIdB: 8, localAnchorA: 16, localAnchorB: 24, localAxisA: 32, enableSpring: 40, hertz: 44, dampingRatio: 48, enableLimit: 52, lowerTranslation: 56, upperTranslation: 60, enableMotor: 64, maxMotorTorque: 68, motorSpeed: 72, collideConnected: 76, userData: 80, internalValue: 88}},
      "ExplosionDef" => {size: 32, alignment: 8, offsets: {maskBits: 0, position: 8, radius: 16, falloff: 20, impulsePerLength: 24}},
      "SensorBeginTouchEvent" => {size: 16, alignment: 4, offsets: {sensorShapeId: 0, visitorShapeId: 8}},
      "SensorEndTouchEvent" => {size: 16, alignment: 4, offsets: {sensorShapeId: 0, visitorShapeId: 8}},
      "SensorEvents" => {size: 24, alignment: 8, offsets: {beginEvents: 0, endEvents: 8, beginCount: 16, endCount: 20}},
      "ContactBeginTouchEvent" => {size: 128, alignment: 4, offsets: {shapeIdA: 0, shapeIdB: 8, manifold: 16}},
      "ContactEndTouchEvent" => {size: 16, alignment: 4, offsets: {shapeIdA: 0, shapeIdB: 8}},
      "ContactHitEvent" => {size: 36, alignment: 4, offsets: {shapeIdA: 0, shapeIdB: 8, point: 16, normal: 24, approachSpeed: 32}},
      "ContactEvents" => {size: 40, alignment: 8, offsets: {beginEvents: 0, endEvents: 8, hitEvents: 16, beginCount: 24, endCount: 28, hitCount: 32}},
      "BodyMoveEvent" => {size: 40, alignment: 8, offsets: {transform: 0, bodyId: 16, userData: 24, fellAsleep: 32}},
      "BodyEvents" => {size: 16, alignment: 8, offsets: {moveEvents: 0, moveCount: 8}},
      "ContactData" => {size: 128, alignment: 4, offsets: {shapeIdA: 0, shapeIdB: 8, manifold: 16}},
      "DebugDraw" => {size: 112, alignment: 8, offsets: {DrawPolygonFcn: 0, DrawSolidPolygonFcn: 8, DrawCircleFcn: 16, DrawSolidCircleFcn: 24, DrawSolidCapsuleFcn: 32, DrawSegmentFcn: 40, DrawTransformFcn: 48, DrawPointFcn: 56, DrawStringFcn: 64, drawingBounds: 72, useDrawingBounds: 88, drawShapes: 89, drawJoints: 90, drawJointExtras: 91, drawBounds: 92, drawMass: 93, drawBodyNames: 94, drawContacts: 95, drawGraphColors: 96, drawContactNormals: 97, drawContactImpulses: 98, drawContactFeatures: 99, drawFrictionImpulses: 100, drawIslands: 101, context: 104}}
    }.freeze

    attach_function :b2SetAllocator, [:pointer, :pointer], :void
    attach_function :b2GetByteCount, [], :int
    attach_function :b2SetAssertFcn, [:pointer], :void
    attach_function :b2GetVersion, [], Version.by_value
    attach_function :b2InternalAssertFcn, [:pointer, :pointer, :int], :int
    attach_function :b2GetTicks, [], :uint64
    attach_function :b2GetMilliseconds, [:uint64], :float
    attach_function :b2GetMillisecondsAndReset, [:pointer], :float
    attach_function :b2Yield, [], :void
    attach_function :b2Hash, [:uint32, :pointer, :int], :uint32
    attach_function :b2Atan2, [:float, :float], :float
    attach_function :b2ComputeCosSin, [:float], CosSin.by_value
    attach_function :b2ComputeRotationBetweenUnitVectors, [Vec2.by_value, Vec2.by_value], Rot.by_value
    attach_function :b2IsValidFloat, [:float], :bool
    attach_function :b2IsValidVec2, [Vec2.by_value], :bool
    attach_function :b2IsValidRotation, [Rot.by_value], :bool
    attach_function :b2IsValidAABB, [AABB.by_value], :bool
    attach_function :b2IsValidPlane, [Plane.by_value], :bool
    attach_function :b2SetLengthUnitsPerMeter, [:float], :void
    attach_function :b2GetLengthUnitsPerMeter, [], :float
    attach_function :b2IsValidRay, [:pointer], :bool
    attach_function :b2MakePolygon, [:pointer, :float], Polygon.by_value
    attach_function :b2MakeOffsetPolygon, [:pointer, Vec2.by_value, Rot.by_value], Polygon.by_value
    attach_function :b2MakeOffsetRoundedPolygon, [:pointer, Vec2.by_value, Rot.by_value, :float], Polygon.by_value
    attach_function :b2MakeSquare, [:float], Polygon.by_value
    attach_function :b2MakeBox, [:float, :float], Polygon.by_value
    attach_function :b2MakeRoundedBox, [:float, :float, :float], Polygon.by_value
    attach_function :b2MakeOffsetBox, [:float, :float, Vec2.by_value, Rot.by_value], Polygon.by_value
    attach_function :b2MakeOffsetRoundedBox, [:float, :float, Vec2.by_value, Rot.by_value, :float], Polygon.by_value
    attach_function :b2TransformPolygon, [Transform.by_value, :pointer], Polygon.by_value
    attach_function :b2ComputeCircleMass, [:pointer, :float], MassData.by_value
    attach_function :b2ComputeCapsuleMass, [:pointer, :float], MassData.by_value
    attach_function :b2ComputePolygonMass, [:pointer, :float], MassData.by_value
    attach_function :b2ComputeCircleAABB, [:pointer, Transform.by_value], AABB.by_value
    attach_function :b2ComputeCapsuleAABB, [:pointer, Transform.by_value], AABB.by_value
    attach_function :b2ComputePolygonAABB, [:pointer, Transform.by_value], AABB.by_value
    attach_function :b2ComputeSegmentAABB, [:pointer, Transform.by_value], AABB.by_value
    attach_function :b2PointInCircle, [Vec2.by_value, :pointer], :bool
    attach_function :b2PointInCapsule, [Vec2.by_value, :pointer], :bool
    attach_function :b2PointInPolygon, [Vec2.by_value, :pointer], :bool
    attach_function :b2RayCastCircle, [:pointer, :pointer], CastOutput.by_value
    attach_function :b2RayCastCapsule, [:pointer, :pointer], CastOutput.by_value
    attach_function :b2RayCastSegment, [:pointer, :pointer, :bool], CastOutput.by_value
    attach_function :b2RayCastPolygon, [:pointer, :pointer], CastOutput.by_value
    attach_function :b2ShapeCastCircle, [:pointer, :pointer], CastOutput.by_value
    attach_function :b2ShapeCastCapsule, [:pointer, :pointer], CastOutput.by_value
    attach_function :b2ShapeCastSegment, [:pointer, :pointer], CastOutput.by_value
    attach_function :b2ShapeCastPolygon, [:pointer, :pointer], CastOutput.by_value
    attach_function :b2ComputeHull, [:pointer, :int], Hull.by_value
    attach_function :b2ValidateHull, [:pointer], :bool
    attach_function :b2SegmentDistance, [Vec2.by_value, Vec2.by_value, Vec2.by_value, Vec2.by_value], SegmentDistanceResult.by_value
    attach_function :b2ShapeDistance, [:pointer, :pointer, :pointer, :int], DistanceOutput.by_value
    attach_function :b2ShapeCast, [:pointer], CastOutput.by_value
    attach_function :b2MakeProxy, [:pointer, :int, :float], ShapeProxy.by_value
    attach_function :b2MakeOffsetProxy, [:pointer, :int, :float, Vec2.by_value, Rot.by_value], ShapeProxy.by_value
    attach_function :b2GetSweepTransform, [:pointer, :float], Transform.by_value
    attach_function :b2TimeOfImpact, [:pointer], TOIOutput.by_value
    attach_function :b2CollideCircles, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollideCapsuleAndCircle, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollideSegmentAndCircle, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollidePolygonAndCircle, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollideCapsules, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollideSegmentAndCapsule, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollidePolygonAndCapsule, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollidePolygons, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollideSegmentAndPolygon, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollideChainSegmentAndCircle, [:pointer, Transform.by_value, :pointer, Transform.by_value], Manifold.by_value
    attach_function :b2CollideChainSegmentAndCapsule, [:pointer, Transform.by_value, :pointer, Transform.by_value, :pointer], Manifold.by_value
    attach_function :b2CollideChainSegmentAndPolygon, [:pointer, Transform.by_value, :pointer, Transform.by_value, :pointer], Manifold.by_value
    attach_function :b2DynamicTree_Create, [], DynamicTree.by_value
    attach_function :b2DynamicTree_Destroy, [:pointer], :void
    attach_function :b2DynamicTree_CreateProxy, [:pointer, AABB.by_value, :uint64, :uint64], :int
    attach_function :b2DynamicTree_DestroyProxy, [:pointer, :int], :void
    attach_function :b2DynamicTree_MoveProxy, [:pointer, :int, AABB.by_value], :void
    attach_function :b2DynamicTree_EnlargeProxy, [:pointer, :int, AABB.by_value], :void
    attach_function :b2DynamicTree_SetCategoryBits, [:pointer, :int, :uint64], :void
    attach_function :b2DynamicTree_GetCategoryBits, [:pointer, :int], :uint64
    attach_function :b2DynamicTree_Query, [:pointer, AABB.by_value, :uint64, :pointer, :pointer], TreeStats.by_value
    attach_function :b2DynamicTree_RayCast, [:pointer, :pointer, :uint64, :pointer, :pointer], TreeStats.by_value
    attach_function :b2DynamicTree_ShapeCast, [:pointer, :pointer, :uint64, :pointer, :pointer], TreeStats.by_value
    attach_function :b2DynamicTree_GetHeight, [:pointer], :int
    attach_function :b2DynamicTree_GetAreaRatio, [:pointer], :float
    attach_function :b2DynamicTree_GetRootBounds, [:pointer], AABB.by_value
    attach_function :b2DynamicTree_GetProxyCount, [:pointer], :int
    attach_function :b2DynamicTree_Rebuild, [:pointer, :bool], :int
    attach_function :b2DynamicTree_GetByteCount, [:pointer], :int
    attach_function :b2DynamicTree_GetUserData, [:pointer, :int], :uint64
    attach_function :b2DynamicTree_GetAABB, [:pointer, :int], AABB.by_value
    attach_function :b2DynamicTree_Validate, [:pointer], :void
    attach_function :b2DynamicTree_ValidateNoEnlarged, [:pointer], :void
    attach_function :b2SolvePlanes, [Vec2.by_value, :pointer, :int], PlaneSolverResult.by_value
    attach_function :b2ClipVector, [Vec2.by_value, :pointer, :int], Vec2.by_value
    attach_function :b2DefaultWorldDef, [], WorldDef.by_value
    attach_function :b2DefaultBodyDef, [], BodyDef.by_value
    attach_function :b2DefaultFilter, [], Filter.by_value
    attach_function :b2DefaultQueryFilter, [], QueryFilter.by_value
    attach_function :b2DefaultSurfaceMaterial, [], SurfaceMaterial.by_value
    attach_function :b2DefaultShapeDef, [], ShapeDef.by_value
    attach_function :b2DefaultChainDef, [], ChainDef.by_value
    attach_function :b2DefaultDistanceJointDef, [], DistanceJointDef.by_value
    attach_function :b2DefaultMotorJointDef, [], MotorJointDef.by_value
    attach_function :b2DefaultMouseJointDef, [], MouseJointDef.by_value
    attach_function :b2DefaultFilterJointDef, [], FilterJointDef.by_value
    attach_function :b2DefaultPrismaticJointDef, [], PrismaticJointDef.by_value
    attach_function :b2DefaultRevoluteJointDef, [], RevoluteJointDef.by_value
    attach_function :b2DefaultWeldJointDef, [], WeldJointDef.by_value
    attach_function :b2DefaultWheelJointDef, [], WheelJointDef.by_value
    attach_function :b2DefaultExplosionDef, [], ExplosionDef.by_value
    attach_function :b2DefaultDebugDraw, [], DebugDraw.by_value
    attach_function :b2CreateWorld, [:pointer], WorldId.by_value
    attach_function :b2DestroyWorld, [WorldId.by_value], :void
    attach_function :b2World_IsValid, [WorldId.by_value], :bool
    attach_function :b2World_Step, [WorldId.by_value, :float, :int], :void, blocking: true
    attach_function :b2World_Draw, [WorldId.by_value, :pointer], :void
    attach_function :b2World_GetBodyEvents, [WorldId.by_value], BodyEvents.by_value
    attach_function :b2World_GetSensorEvents, [WorldId.by_value], SensorEvents.by_value
    attach_function :b2World_GetContactEvents, [WorldId.by_value], ContactEvents.by_value
    attach_function :b2World_OverlapAABB, [WorldId.by_value, AABB.by_value, QueryFilter.by_value, :pointer, :pointer], TreeStats.by_value
    attach_function :b2World_OverlapShape, [WorldId.by_value, :pointer, QueryFilter.by_value, :pointer, :pointer], TreeStats.by_value
    attach_function :b2World_CastRay, [WorldId.by_value, Vec2.by_value, Vec2.by_value, QueryFilter.by_value, :pointer, :pointer], TreeStats.by_value
    attach_function :b2World_CastRayClosest, [WorldId.by_value, Vec2.by_value, Vec2.by_value, QueryFilter.by_value], RayResult.by_value
    attach_function :b2World_CastShape, [WorldId.by_value, :pointer, Vec2.by_value, QueryFilter.by_value, :pointer, :pointer], TreeStats.by_value
    attach_function :b2World_CastMover, [WorldId.by_value, :pointer, Vec2.by_value, QueryFilter.by_value], :float
    attach_function :b2World_CollideMover, [WorldId.by_value, :pointer, QueryFilter.by_value, :pointer, :pointer], :void
    attach_function :b2World_EnableSleeping, [WorldId.by_value, :bool], :void
    attach_function :b2World_IsSleepingEnabled, [WorldId.by_value], :bool
    attach_function :b2World_EnableContinuous, [WorldId.by_value, :bool], :void
    attach_function :b2World_IsContinuousEnabled, [WorldId.by_value], :bool
    attach_function :b2World_SetRestitutionThreshold, [WorldId.by_value, :float], :void
    attach_function :b2World_GetRestitutionThreshold, [WorldId.by_value], :float
    attach_function :b2World_SetHitEventThreshold, [WorldId.by_value, :float], :void
    attach_function :b2World_GetHitEventThreshold, [WorldId.by_value], :float
    attach_function :b2World_SetCustomFilterCallback, [WorldId.by_value, :pointer, :pointer], :void
    attach_function :b2World_SetPreSolveCallback, [WorldId.by_value, :pointer, :pointer], :void
    attach_function :b2World_SetGravity, [WorldId.by_value, Vec2.by_value], :void
    attach_function :b2World_GetGravity, [WorldId.by_value], Vec2.by_value
    attach_function :b2World_Explode, [WorldId.by_value, :pointer], :void
    attach_function :b2World_SetContactTuning, [WorldId.by_value, :float, :float, :float], :void
    attach_function :b2World_SetJointTuning, [WorldId.by_value, :float, :float], :void
    attach_function :b2World_SetMaximumLinearSpeed, [WorldId.by_value, :float], :void
    attach_function :b2World_GetMaximumLinearSpeed, [WorldId.by_value], :float
    attach_function :b2World_EnableWarmStarting, [WorldId.by_value, :bool], :void
    attach_function :b2World_IsWarmStartingEnabled, [WorldId.by_value], :bool
    attach_function :b2World_GetAwakeBodyCount, [WorldId.by_value], :int
    attach_function :b2World_GetProfile, [WorldId.by_value], Profile.by_value
    attach_function :b2World_GetCounters, [WorldId.by_value], Counters.by_value
    attach_function :b2World_SetUserData, [WorldId.by_value, :pointer], :void
    attach_function :b2World_GetUserData, [WorldId.by_value], :pointer
    attach_function :b2World_SetFrictionCallback, [WorldId.by_value, :pointer], :void
    attach_function :b2World_SetRestitutionCallback, [WorldId.by_value, :pointer], :void
    attach_function :b2World_DumpMemoryStats, [WorldId.by_value], :void
    attach_function :b2World_RebuildStaticTree, [WorldId.by_value], :void
    attach_function :b2World_EnableSpeculative, [WorldId.by_value, :bool], :void
    attach_function :b2CreateBody, [WorldId.by_value, :pointer], BodyId.by_value
    attach_function :b2DestroyBody, [BodyId.by_value], :void
    attach_function :b2Body_IsValid, [BodyId.by_value], :bool
    attach_function :b2Body_GetType, [BodyId.by_value], :int
    attach_function :b2Body_SetType, [BodyId.by_value, :int], :void
    attach_function :b2Body_SetName, [BodyId.by_value, :pointer], :void
    attach_function :b2Body_GetName, [BodyId.by_value], :pointer
    attach_function :b2Body_SetUserData, [BodyId.by_value, :pointer], :void
    attach_function :b2Body_GetUserData, [BodyId.by_value], :pointer
    attach_function :b2Body_GetPosition, [BodyId.by_value], Vec2.by_value
    attach_function :b2Body_GetRotation, [BodyId.by_value], Rot.by_value
    attach_function :b2Body_GetTransform, [BodyId.by_value], Transform.by_value
    attach_function :b2Body_SetTransform, [BodyId.by_value, Vec2.by_value, Rot.by_value], :void
    attach_function :b2Body_GetLocalPoint, [BodyId.by_value, Vec2.by_value], Vec2.by_value
    attach_function :b2Body_GetWorldPoint, [BodyId.by_value, Vec2.by_value], Vec2.by_value
    attach_function :b2Body_GetLocalVector, [BodyId.by_value, Vec2.by_value], Vec2.by_value
    attach_function :b2Body_GetWorldVector, [BodyId.by_value, Vec2.by_value], Vec2.by_value
    attach_function :b2Body_GetLinearVelocity, [BodyId.by_value], Vec2.by_value
    attach_function :b2Body_GetAngularVelocity, [BodyId.by_value], :float
    attach_function :b2Body_SetLinearVelocity, [BodyId.by_value, Vec2.by_value], :void
    attach_function :b2Body_SetAngularVelocity, [BodyId.by_value, :float], :void
    attach_function :b2Body_SetTargetTransform, [BodyId.by_value, Transform.by_value, :float], :void
    attach_function :b2Body_GetLocalPointVelocity, [BodyId.by_value, Vec2.by_value], Vec2.by_value
    attach_function :b2Body_GetWorldPointVelocity, [BodyId.by_value, Vec2.by_value], Vec2.by_value
    attach_function :b2Body_ApplyForce, [BodyId.by_value, Vec2.by_value, Vec2.by_value, :bool], :void
    attach_function :b2Body_ApplyForceToCenter, [BodyId.by_value, Vec2.by_value, :bool], :void
    attach_function :b2Body_ApplyTorque, [BodyId.by_value, :float, :bool], :void
    attach_function :b2Body_ApplyLinearImpulse, [BodyId.by_value, Vec2.by_value, Vec2.by_value, :bool], :void
    attach_function :b2Body_ApplyLinearImpulseToCenter, [BodyId.by_value, Vec2.by_value, :bool], :void
    attach_function :b2Body_ApplyAngularImpulse, [BodyId.by_value, :float, :bool], :void
    attach_function :b2Body_GetMass, [BodyId.by_value], :float
    attach_function :b2Body_GetRotationalInertia, [BodyId.by_value], :float
    attach_function :b2Body_GetLocalCenterOfMass, [BodyId.by_value], Vec2.by_value
    attach_function :b2Body_GetWorldCenterOfMass, [BodyId.by_value], Vec2.by_value
    attach_function :b2Body_SetMassData, [BodyId.by_value, MassData.by_value], :void
    attach_function :b2Body_GetMassData, [BodyId.by_value], MassData.by_value
    attach_function :b2Body_ApplyMassFromShapes, [BodyId.by_value], :void
    attach_function :b2Body_SetLinearDamping, [BodyId.by_value, :float], :void
    attach_function :b2Body_GetLinearDamping, [BodyId.by_value], :float
    attach_function :b2Body_SetAngularDamping, [BodyId.by_value, :float], :void
    attach_function :b2Body_GetAngularDamping, [BodyId.by_value], :float
    attach_function :b2Body_SetGravityScale, [BodyId.by_value, :float], :void
    attach_function :b2Body_GetGravityScale, [BodyId.by_value], :float
    attach_function :b2Body_IsAwake, [BodyId.by_value], :bool
    attach_function :b2Body_SetAwake, [BodyId.by_value, :bool], :void
    attach_function :b2Body_EnableSleep, [BodyId.by_value, :bool], :void
    attach_function :b2Body_IsSleepEnabled, [BodyId.by_value], :bool
    attach_function :b2Body_SetSleepThreshold, [BodyId.by_value, :float], :void
    attach_function :b2Body_GetSleepThreshold, [BodyId.by_value], :float
    attach_function :b2Body_IsEnabled, [BodyId.by_value], :bool
    attach_function :b2Body_Disable, [BodyId.by_value], :void
    attach_function :b2Body_Enable, [BodyId.by_value], :void
    attach_function :b2Body_SetFixedRotation, [BodyId.by_value, :bool], :void
    attach_function :b2Body_IsFixedRotation, [BodyId.by_value], :bool
    attach_function :b2Body_SetBullet, [BodyId.by_value, :bool], :void
    attach_function :b2Body_IsBullet, [BodyId.by_value], :bool
    attach_function :b2Body_EnableContactEvents, [BodyId.by_value, :bool], :void
    attach_function :b2Body_EnableHitEvents, [BodyId.by_value, :bool], :void
    attach_function :b2Body_GetWorld, [BodyId.by_value], WorldId.by_value
    attach_function :b2Body_GetShapeCount, [BodyId.by_value], :int
    attach_function :b2Body_GetShapes, [BodyId.by_value, :pointer, :int], :int
    attach_function :b2Body_GetJointCount, [BodyId.by_value], :int
    attach_function :b2Body_GetJoints, [BodyId.by_value, :pointer, :int], :int
    attach_function :b2Body_GetContactCapacity, [BodyId.by_value], :int
    attach_function :b2Body_GetContactData, [BodyId.by_value, :pointer, :int], :int
    attach_function :b2Body_ComputeAABB, [BodyId.by_value], AABB.by_value
    attach_function :b2CreateCircleShape, [BodyId.by_value, :pointer, :pointer], ShapeId.by_value
    attach_function :b2CreateSegmentShape, [BodyId.by_value, :pointer, :pointer], ShapeId.by_value
    attach_function :b2CreateCapsuleShape, [BodyId.by_value, :pointer, :pointer], ShapeId.by_value
    attach_function :b2CreatePolygonShape, [BodyId.by_value, :pointer, :pointer], ShapeId.by_value
    attach_function :b2DestroyShape, [ShapeId.by_value, :bool], :void
    attach_function :b2Shape_IsValid, [ShapeId.by_value], :bool
    attach_function :b2Shape_GetType, [ShapeId.by_value], :int
    attach_function :b2Shape_GetBody, [ShapeId.by_value], BodyId.by_value
    attach_function :b2Shape_GetWorld, [ShapeId.by_value], WorldId.by_value
    attach_function :b2Shape_IsSensor, [ShapeId.by_value], :bool
    attach_function :b2Shape_SetUserData, [ShapeId.by_value, :pointer], :void
    attach_function :b2Shape_GetUserData, [ShapeId.by_value], :pointer
    attach_function :b2Shape_SetDensity, [ShapeId.by_value, :float, :bool], :void
    attach_function :b2Shape_GetDensity, [ShapeId.by_value], :float
    attach_function :b2Shape_SetFriction, [ShapeId.by_value, :float], :void
    attach_function :b2Shape_GetFriction, [ShapeId.by_value], :float
    attach_function :b2Shape_SetRestitution, [ShapeId.by_value, :float], :void
    attach_function :b2Shape_GetRestitution, [ShapeId.by_value], :float
    attach_function :b2Shape_SetMaterial, [ShapeId.by_value, :int], :void
    attach_function :b2Shape_GetMaterial, [ShapeId.by_value], :int
    attach_function :b2Shape_GetFilter, [ShapeId.by_value], Filter.by_value
    attach_function :b2Shape_SetFilter, [ShapeId.by_value, Filter.by_value], :void
    attach_function :b2Shape_EnableSensorEvents, [ShapeId.by_value, :bool], :void
    attach_function :b2Shape_AreSensorEventsEnabled, [ShapeId.by_value], :bool
    attach_function :b2Shape_EnableContactEvents, [ShapeId.by_value, :bool], :void
    attach_function :b2Shape_AreContactEventsEnabled, [ShapeId.by_value], :bool
    attach_function :b2Shape_EnablePreSolveEvents, [ShapeId.by_value, :bool], :void
    attach_function :b2Shape_ArePreSolveEventsEnabled, [ShapeId.by_value], :bool
    attach_function :b2Shape_EnableHitEvents, [ShapeId.by_value, :bool], :void
    attach_function :b2Shape_AreHitEventsEnabled, [ShapeId.by_value], :bool
    attach_function :b2Shape_TestPoint, [ShapeId.by_value, Vec2.by_value], :bool
    attach_function :b2Shape_RayCast, [ShapeId.by_value, :pointer], CastOutput.by_value
    attach_function :b2Shape_GetCircle, [ShapeId.by_value], Circle.by_value
    attach_function :b2Shape_GetSegment, [ShapeId.by_value], Segment.by_value
    attach_function :b2Shape_GetChainSegment, [ShapeId.by_value], ChainSegment.by_value
    attach_function :b2Shape_GetCapsule, [ShapeId.by_value], Capsule.by_value
    attach_function :b2Shape_GetPolygon, [ShapeId.by_value], Polygon.by_value
    attach_function :b2Shape_SetCircle, [ShapeId.by_value, :pointer], :void
    attach_function :b2Shape_SetCapsule, [ShapeId.by_value, :pointer], :void
    attach_function :b2Shape_SetSegment, [ShapeId.by_value, :pointer], :void
    attach_function :b2Shape_SetPolygon, [ShapeId.by_value, :pointer], :void
    attach_function :b2Shape_GetParentChain, [ShapeId.by_value], ChainId.by_value
    attach_function :b2Shape_GetContactCapacity, [ShapeId.by_value], :int
    attach_function :b2Shape_GetContactData, [ShapeId.by_value, :pointer, :int], :int
    attach_function :b2Shape_GetSensorCapacity, [ShapeId.by_value], :int
    attach_function :b2Shape_GetSensorOverlaps, [ShapeId.by_value, :pointer, :int], :int
    attach_function :b2Shape_GetAABB, [ShapeId.by_value], AABB.by_value
    attach_function :b2Shape_GetMassData, [ShapeId.by_value], MassData.by_value
    attach_function :b2Shape_GetClosestPoint, [ShapeId.by_value, Vec2.by_value], Vec2.by_value
    attach_function :b2CreateChain, [BodyId.by_value, :pointer], ChainId.by_value
    attach_function :b2DestroyChain, [ChainId.by_value], :void
    attach_function :b2Chain_GetWorld, [ChainId.by_value], WorldId.by_value
    attach_function :b2Chain_GetSegmentCount, [ChainId.by_value], :int
    attach_function :b2Chain_GetSegments, [ChainId.by_value, :pointer, :int], :int
    attach_function :b2Chain_SetFriction, [ChainId.by_value, :float], :void
    attach_function :b2Chain_GetFriction, [ChainId.by_value], :float
    attach_function :b2Chain_SetRestitution, [ChainId.by_value, :float], :void
    attach_function :b2Chain_GetRestitution, [ChainId.by_value], :float
    attach_function :b2Chain_SetMaterial, [ChainId.by_value, :int], :void
    attach_function :b2Chain_GetMaterial, [ChainId.by_value], :int
    attach_function :b2Chain_IsValid, [ChainId.by_value], :bool
    attach_function :b2DestroyJoint, [JointId.by_value], :void
    attach_function :b2Joint_IsValid, [JointId.by_value], :bool
    attach_function :b2Joint_GetType, [JointId.by_value], :int
    attach_function :b2Joint_GetBodyA, [JointId.by_value], BodyId.by_value
    attach_function :b2Joint_GetBodyB, [JointId.by_value], BodyId.by_value
    attach_function :b2Joint_GetWorld, [JointId.by_value], WorldId.by_value
    attach_function :b2Joint_GetLocalAnchorA, [JointId.by_value], Vec2.by_value
    attach_function :b2Joint_GetLocalAnchorB, [JointId.by_value], Vec2.by_value
    attach_function :b2Joint_SetCollideConnected, [JointId.by_value, :bool], :void
    attach_function :b2Joint_GetCollideConnected, [JointId.by_value], :bool
    attach_function :b2Joint_SetUserData, [JointId.by_value, :pointer], :void
    attach_function :b2Joint_GetUserData, [JointId.by_value], :pointer
    attach_function :b2Joint_WakeBodies, [JointId.by_value], :void
    attach_function :b2Joint_GetConstraintForce, [JointId.by_value], Vec2.by_value
    attach_function :b2Joint_GetConstraintTorque, [JointId.by_value], :float
    attach_function :b2CreateDistanceJoint, [WorldId.by_value, :pointer], JointId.by_value
    attach_function :b2DistanceJoint_SetLength, [JointId.by_value, :float], :void
    attach_function :b2DistanceJoint_GetLength, [JointId.by_value], :float
    attach_function :b2DistanceJoint_EnableSpring, [JointId.by_value, :bool], :void
    attach_function :b2DistanceJoint_IsSpringEnabled, [JointId.by_value], :bool
    attach_function :b2DistanceJoint_SetSpringHertz, [JointId.by_value, :float], :void
    attach_function :b2DistanceJoint_SetSpringDampingRatio, [JointId.by_value, :float], :void
    attach_function :b2DistanceJoint_GetSpringHertz, [JointId.by_value], :float
    attach_function :b2DistanceJoint_GetSpringDampingRatio, [JointId.by_value], :float
    attach_function :b2DistanceJoint_EnableLimit, [JointId.by_value, :bool], :void
    attach_function :b2DistanceJoint_IsLimitEnabled, [JointId.by_value], :bool
    attach_function :b2DistanceJoint_SetLengthRange, [JointId.by_value, :float, :float], :void
    attach_function :b2DistanceJoint_GetMinLength, [JointId.by_value], :float
    attach_function :b2DistanceJoint_GetMaxLength, [JointId.by_value], :float
    attach_function :b2DistanceJoint_GetCurrentLength, [JointId.by_value], :float
    attach_function :b2DistanceJoint_EnableMotor, [JointId.by_value, :bool], :void
    attach_function :b2DistanceJoint_IsMotorEnabled, [JointId.by_value], :bool
    attach_function :b2DistanceJoint_SetMotorSpeed, [JointId.by_value, :float], :void
    attach_function :b2DistanceJoint_GetMotorSpeed, [JointId.by_value], :float
    attach_function :b2DistanceJoint_SetMaxMotorForce, [JointId.by_value, :float], :void
    attach_function :b2DistanceJoint_GetMaxMotorForce, [JointId.by_value], :float
    attach_function :b2DistanceJoint_GetMotorForce, [JointId.by_value], :float
    attach_function :b2CreateMotorJoint, [WorldId.by_value, :pointer], JointId.by_value
    attach_function :b2MotorJoint_SetLinearOffset, [JointId.by_value, Vec2.by_value], :void
    attach_function :b2MotorJoint_GetLinearOffset, [JointId.by_value], Vec2.by_value
    attach_function :b2MotorJoint_SetAngularOffset, [JointId.by_value, :float], :void
    attach_function :b2MotorJoint_GetAngularOffset, [JointId.by_value], :float
    attach_function :b2MotorJoint_SetMaxForce, [JointId.by_value, :float], :void
    attach_function :b2MotorJoint_GetMaxForce, [JointId.by_value], :float
    attach_function :b2MotorJoint_SetMaxTorque, [JointId.by_value, :float], :void
    attach_function :b2MotorJoint_GetMaxTorque, [JointId.by_value], :float
    attach_function :b2MotorJoint_SetCorrectionFactor, [JointId.by_value, :float], :void
    attach_function :b2MotorJoint_GetCorrectionFactor, [JointId.by_value], :float
    attach_function :b2CreateMouseJoint, [WorldId.by_value, :pointer], JointId.by_value
    attach_function :b2MouseJoint_SetTarget, [JointId.by_value, Vec2.by_value], :void
    attach_function :b2MouseJoint_GetTarget, [JointId.by_value], Vec2.by_value
    attach_function :b2MouseJoint_SetSpringHertz, [JointId.by_value, :float], :void
    attach_function :b2MouseJoint_GetSpringHertz, [JointId.by_value], :float
    attach_function :b2MouseJoint_SetSpringDampingRatio, [JointId.by_value, :float], :void
    attach_function :b2MouseJoint_GetSpringDampingRatio, [JointId.by_value], :float
    attach_function :b2MouseJoint_SetMaxForce, [JointId.by_value, :float], :void
    attach_function :b2MouseJoint_GetMaxForce, [JointId.by_value], :float
    attach_function :b2CreateFilterJoint, [WorldId.by_value, :pointer], JointId.by_value
    attach_function :b2CreatePrismaticJoint, [WorldId.by_value, :pointer], JointId.by_value
    attach_function :b2PrismaticJoint_EnableSpring, [JointId.by_value, :bool], :void
    attach_function :b2PrismaticJoint_IsSpringEnabled, [JointId.by_value], :bool
    attach_function :b2PrismaticJoint_SetSpringHertz, [JointId.by_value, :float], :void
    attach_function :b2PrismaticJoint_GetSpringHertz, [JointId.by_value], :float
    attach_function :b2PrismaticJoint_SetSpringDampingRatio, [JointId.by_value, :float], :void
    attach_function :b2PrismaticJoint_GetSpringDampingRatio, [JointId.by_value], :float
    attach_function :b2PrismaticJoint_EnableLimit, [JointId.by_value, :bool], :void
    attach_function :b2PrismaticJoint_IsLimitEnabled, [JointId.by_value], :bool
    attach_function :b2PrismaticJoint_GetLowerLimit, [JointId.by_value], :float
    attach_function :b2PrismaticJoint_GetUpperLimit, [JointId.by_value], :float
    attach_function :b2PrismaticJoint_SetLimits, [JointId.by_value, :float, :float], :void
    attach_function :b2PrismaticJoint_EnableMotor, [JointId.by_value, :bool], :void
    attach_function :b2PrismaticJoint_IsMotorEnabled, [JointId.by_value], :bool
    attach_function :b2PrismaticJoint_SetMotorSpeed, [JointId.by_value, :float], :void
    attach_function :b2PrismaticJoint_GetMotorSpeed, [JointId.by_value], :float
    attach_function :b2PrismaticJoint_SetMaxMotorForce, [JointId.by_value, :float], :void
    attach_function :b2PrismaticJoint_GetMaxMotorForce, [JointId.by_value], :float
    attach_function :b2PrismaticJoint_GetMotorForce, [JointId.by_value], :float
    attach_function :b2PrismaticJoint_GetTranslation, [JointId.by_value], :float
    attach_function :b2PrismaticJoint_GetSpeed, [JointId.by_value], :float
    attach_function :b2CreateRevoluteJoint, [WorldId.by_value, :pointer], JointId.by_value
    attach_function :b2RevoluteJoint_EnableSpring, [JointId.by_value, :bool], :void
    attach_function :b2RevoluteJoint_IsSpringEnabled, [JointId.by_value], :bool
    attach_function :b2RevoluteJoint_SetSpringHertz, [JointId.by_value, :float], :void
    attach_function :b2RevoluteJoint_GetSpringHertz, [JointId.by_value], :float
    attach_function :b2RevoluteJoint_SetSpringDampingRatio, [JointId.by_value, :float], :void
    attach_function :b2RevoluteJoint_GetSpringDampingRatio, [JointId.by_value], :float
    attach_function :b2RevoluteJoint_GetAngle, [JointId.by_value], :float
    attach_function :b2RevoluteJoint_EnableLimit, [JointId.by_value, :bool], :void
    attach_function :b2RevoluteJoint_IsLimitEnabled, [JointId.by_value], :bool
    attach_function :b2RevoluteJoint_GetLowerLimit, [JointId.by_value], :float
    attach_function :b2RevoluteJoint_GetUpperLimit, [JointId.by_value], :float
    attach_function :b2RevoluteJoint_SetLimits, [JointId.by_value, :float, :float], :void
    attach_function :b2RevoluteJoint_EnableMotor, [JointId.by_value, :bool], :void
    attach_function :b2RevoluteJoint_IsMotorEnabled, [JointId.by_value], :bool
    attach_function :b2RevoluteJoint_SetMotorSpeed, [JointId.by_value, :float], :void
    attach_function :b2RevoluteJoint_GetMotorSpeed, [JointId.by_value], :float
    attach_function :b2RevoluteJoint_GetMotorTorque, [JointId.by_value], :float
    attach_function :b2RevoluteJoint_SetMaxMotorTorque, [JointId.by_value, :float], :void
    attach_function :b2RevoluteJoint_GetMaxMotorTorque, [JointId.by_value], :float
    attach_function :b2CreateWeldJoint, [WorldId.by_value, :pointer], JointId.by_value
    attach_function :b2WeldJoint_GetReferenceAngle, [JointId.by_value], :float
    attach_function :b2WeldJoint_SetReferenceAngle, [JointId.by_value, :float], :void
    attach_function :b2WeldJoint_SetLinearHertz, [JointId.by_value, :float], :void
    attach_function :b2WeldJoint_GetLinearHertz, [JointId.by_value], :float
    attach_function :b2WeldJoint_SetLinearDampingRatio, [JointId.by_value, :float], :void
    attach_function :b2WeldJoint_GetLinearDampingRatio, [JointId.by_value], :float
    attach_function :b2WeldJoint_SetAngularHertz, [JointId.by_value, :float], :void
    attach_function :b2WeldJoint_GetAngularHertz, [JointId.by_value], :float
    attach_function :b2WeldJoint_SetAngularDampingRatio, [JointId.by_value, :float], :void
    attach_function :b2WeldJoint_GetAngularDampingRatio, [JointId.by_value], :float
    attach_function :b2CreateWheelJoint, [WorldId.by_value, :pointer], JointId.by_value
    attach_function :b2WheelJoint_EnableSpring, [JointId.by_value, :bool], :void
    attach_function :b2WheelJoint_IsSpringEnabled, [JointId.by_value], :bool
    attach_function :b2WheelJoint_SetSpringHertz, [JointId.by_value, :float], :void
    attach_function :b2WheelJoint_GetSpringHertz, [JointId.by_value], :float
    attach_function :b2WheelJoint_SetSpringDampingRatio, [JointId.by_value, :float], :void
    attach_function :b2WheelJoint_GetSpringDampingRatio, [JointId.by_value], :float
    attach_function :b2WheelJoint_EnableLimit, [JointId.by_value, :bool], :void
    attach_function :b2WheelJoint_IsLimitEnabled, [JointId.by_value], :bool
    attach_function :b2WheelJoint_GetLowerLimit, [JointId.by_value], :float
    attach_function :b2WheelJoint_GetUpperLimit, [JointId.by_value], :float
    attach_function :b2WheelJoint_SetLimits, [JointId.by_value, :float, :float], :void
    attach_function :b2WheelJoint_EnableMotor, [JointId.by_value, :bool], :void
    attach_function :b2WheelJoint_IsMotorEnabled, [JointId.by_value], :bool
    attach_function :b2WheelJoint_SetMotorSpeed, [JointId.by_value, :float], :void
    attach_function :b2WheelJoint_GetMotorSpeed, [JointId.by_value], :float
    attach_function :b2WheelJoint_SetMaxMotorTorque, [JointId.by_value, :float], :void
    attach_function :b2WheelJoint_GetMaxMotorTorque, [JointId.by_value], :float
    attach_function :b2WheelJoint_GetMotorTorque, [JointId.by_value], :float
  end
end
