name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ruby 3.2 / x86_64 Linux
            os: ubuntu-24.04
            ruby: "3.2"
          - name: Ruby 3.4 / x86_64 Linux
            os: ubuntu-24.04
            ruby: "3.4"
          - name: Ruby 4.0 / x86_64 Linux
            os: ubuntu-24.04
            ruby: "4.0"
          - name: Ruby 4.0 / aarch64 Linux
            os: ubuntu-24.04-arm
            ruby: "4.0"
          - name: Ruby 4.0 / arm64 macOS
            os: macos-15
            ruby: "4.0"
          - name: Ruby 4.0 / x86_64 macOS
            os: macos-15-intel
            ruby: "4.0"
          - name: Ruby 4.0 / x64 Windows
            os: windows-2025
            ruby: "4.0"

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
